no1=int(input("Enter an integer: "))
no2=float(input("Enter a decimal number: "))
name=str(input("Enter a string value: "))
print("")
print("Integer is: ",no1)
print("Decimal number is: ",no2)
print("String value is: ",name)
