SELECT DISTINCT INSTRUCTOR.Id, INSTRUCTOR.IName, INSTRUCTOR.IOffice, INSTRUCTOR.IPhone, INSTRUCTOR.Rank
FROM SECTION
JOIN INSTRUCTOR ON SECTION.InstructorId = INSTRUCTOR.Id
JOIN COURSE ON SECTION.CourseCCode = COURSE.CCode
WHERE COURSE.Level = 'SpecificLevel'; -- Replace 'SpecificLevel' with the actual course level
